login_django/login_app/urls.py
from django.urls import path 
from login_app import views 

app_name='login_app'

urlpatterns = [
    path('registration/', views.registration, name='register'),
    path('user_login/', views.user_login, name='user_login'),
]

login_django/login_django/urls.py
from django.contrib import admin
from django.urls import path,include
from login_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('login_app/', include('login_app.urls')),
    path('logout/', views.user_logout, name='logout'),
]

login_django/login_app/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
	user = models.OneToOneField(User, on_delete=models.DO_NOTHING)
	portfolio = models.URLField(blank=True)
	picture = models.ImageField(blank=True)
	picture = models.ImageField(upload_to='profile_pics', blank=True)


	def __str__(self):
		return self.user.username
		
# Create your models here.

login_django/login_app/forms.py
from django import forms 
from django.contrib.auth.models import User 
from login_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User 
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    portfolio = forms.URLField(required=False)
    picture = forms.ImageField(required=False)

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio', 'picture')

        

login_django/login_app/views.py
from django.shortcuts import render
from login_app.forms import UserForm, UserProfileInfoForm
from django.urls import reverse 
from django.contrib.auth.decorators import login_required 
from django.http import HttpResponseRedirect, HttpResponse 
from django.contrib.auth import login, logout, authenticate

def index(request):
    context = {
    }
    return render(request, 'login_app/index.html', context )



def registration(request):
    registered = False 
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    context = { 
        'user_form':user_form,
        'profile_form':profile_form,
        'registered':registered,
    }

    return render(request, 'login_app/registration.html', context)

def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account is not active')
        else:
            print('someone tried to login and failed ')
            return HttpResponse('Invalid login details')
    else:
        return render(request, 'login_app/login.html', {})

def user_logout(request):

    logout(request)
    return HttpResponseRedirect(reverse('index'))



        

login_django/templates/login_app/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Project</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default navbar-default navbar-static-top"></nav>
    <div class="container">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'index' %}">Brand</a></li>
            <li><a class="navbar-admin" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-register" href="{% url 'login_app:register'%}">Registration</a></li>
            {% if  user.is_authenticated %}
            <li><a class="navbar-admin" href = "{% url 'logout' %}">Logout</a></li>
            {% else %}
            <li><a class="navbar-register" href="{% url 'login_app:user_login'%}">Login</a></li>
            {% endif %}
        </ul>
    </div>
    <div class='container'>
        {% block body_block %}

        {% endblock %}
    </div>
</body>
</html>

login_django/templates/login_app/index.html
{% extends 'login_app/base.html' %}

{% block body_block %}

<div class="jumbotron">
    <h1>{{ user|upper }}'s My django login app</h1>

</div>
{% endblock %}

login_django/templates/login_app/login.html
{% extends 'login_app/base.html' %}

{% block body_block %} 
<div class="jumbotron">
    <h1>Please login to site!</h1>
    <form action = "{% url 'login_app:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" value="Login">
    </form>
</div>
{% endblock %}

login_django/templates/login_app/registration.html
{% extends 'login_app/base.html' %}

{% block body_block %}

<div class="jumbotron">
    {% if registered %}
    <h1>Thank you for registering!</h1>
    {% else %}

    <h1> Register Here</h1>
    <h3>Fill out the form:</h3>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{user_form.as_p}}
        {{profile_form.as_p}}
        <input type="submit" value="Register">
    </form>
    {% endif %}
</div>
{% endblock %}